schemaVersion: "2.0.0"

commandTests:
  - name: "IBM Cloud CLI installation"
    command: "ibmcloud"
    args: ["--help"]
    expectedOutput: ["NAME:\n.*ibmcloud.*"]

  - name: "IBM Cloud container-service plugin"
    command: "ibmcloud"
    args: ["plugin", "list"]
    expectedOutput: [".*container-service/kubernetes-service.*"]

  - name: "IBM Cloud container-registry plugin"
    command: "ibmcloud"
    args: ["plugin", "list"]
    expectedOutput: [".*container-registry.*"]

  - name: "Kubectl CLI installation"
    command: "kubectl"
    args: ["version", "--client=true"]
    expectedOutput: ["Client Version.*"]

  - name: "Helm CLI installation"
    command: "helm"
    args: ["version", "-c"]
    expectedOutput: ["Client.*"]

  - name: "Git installation"
    command: "git"
    args: ["version"]
    expectedOutput: ["git version.*"]
